name: AetaCraft
main: main.Main
version: 1.00 
commands:
 class:
  description: commands for classes
 untame:
  description: if this is active right-clicking a wolf or cat untames it
 pray:
  description: call upon your god for aid
 trade:
  description: experience